### ISSUE TITLE
Feature/Import code through git

### ISSUE THREAD

**Issue by vinay-ghate** [Gitesh08/code-caliber-ai#1]
Add a option to add GitHub repo link so user can insert link and get Documentation to upload on his repo.

**Comment by Gitesh08** [comment]
Hello @vinay-ghate, 

Thank you for good suggestion! I have updated codebase for this enhancement now Code Caliber AI is ready to accept Github Repository as well.

Closing this issue as feature has updated in codebase. Cheers!

**Comment by Gitesh08** [comment]
Hello @vinay-ghate, 

Thank you for good suggestion! I have updated codebase for this enhancement now Code Caliber AI is ready to accept Github Repository as well.

Closing this issue as feature has updated in codebase. Cheers!
